// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n=1;
		int countMore=0;
		int countLess=0;

		while(n<=100)
		{
			if(Math.random()>0.5)
				countMore++;
			else
				countLess++;
			n++;
		}
		System.out.println("> 0.5: " + countMore + " times");
		System.out.println("<= 0.5: " + countLess + " times");

		if (countLess!=0)
			System.out.println("Ratio: "+ ((double)countMore)/countLess);

	}
}
